gitGraph
    commit id: "Ch2: Basics"
    commit id: "Ch3: Ownership"
    commit id: "Ch4: Control"
    branch stack-project
    checkout stack-project
    commit id: "Ch5: Stack"
    commit id: "Reverse fn"
    checkout main
    merge stack-project
    commit id: "Ch6: Structs"
    commit id: "Ch7: Iterators"
    commit id: "Ch8: Modules"
    commit id: "Ch9: Pointers"
    branch concurrency
    checkout concurrency
    commit id: "Ch14: Threads"
    commit id: "Channels"
    checkout main
    merge concurrency
    commit id: "Ch24: Blockchain"
