timeline
    title Lifetime Annotation Example
    
    section Function Start
        x received : lifetime 'a starts
        y received : 'a continues
    
    section Function Body
        compare lengths : 'a valid
        return reference : 'a continues
    
    section Function End
        return to caller : 'a ends
        parameters drop : 'a complete
